#176 Added nr of failed and succeeded tests per testcase
marklogic-community/marklogic-unit-test pull request #179
Opened 2023-08-09 15:30 UTC by peetkes

I added the number of failed and succeeded tests to he testcase as that will give more info on the cicd pipeline for GitLab when we update the test reports

2023-08-09 16:25 UTC, rjrudin requested changes
This is a good start, I just had some small comments. But it also needs tests added - i.e. at least one scenario where multiple failures are returned. I can add those if you're short on time, which also helps me verify that everything is working correctly.

2023-08-09 16:25 UTC, rjrudin commented on marklogic-unit-test-client/src/main/java/com/marklogic/test/unit/JUnitTestCase.java
> +  private int tests;
Can you make sure your editor is using the .editorconfig file in this repository? We don't want any changes here due to different whitespace (of course these new lines are fine, but they should use the same formatting as existing lines).

2023-08-09 16:25 UTC, rjrudin commented on marklogic-unit-test-client/src/main/java/com/marklogic/test/unit/JaxpServiceResponseUnmarshaller.java
> +      List<Element> successNodes = new ArrayList<>();
Looks like we only care about the number of successes, so this should be an `int` instead of a list.

2023-08-09 16:25 UTC, rjrudin commented on marklogic-unit-test-client/src/main/java/com/marklogic/test/unit/JaxpServiceResponseUnmarshaller.java
> +          if (resultNode.getTagName().equalsIgnoreCase("test:result")) {
It seems safer to do this:

    if ("result".equals(resultNode.getLocalName())

That way, we're not assuming that a particular namespace prefix is being used. And the only issue would be if there's somehow a "result" element in a different namespace, which seems very unlikely - though we could check that as well.

2023-08-09 16:25 UTC, rjrudin commented on marklogic-unit-test-client/src/main/java/com/marklogic/test/unit/TestResult.java
> +  private int success;
"success" should be "succeeded" to match the tense of "failed" - but those sound like booleans. I think we need "count" as a suffix on all of these to make it clear what they're capturing. 

So `testCount`, `successCount`, and `failureCount`. They can also all be `final` as well, in addition to the existing 3 fields.

2023-08-09 16:25 UTC, rjrudin commented on marklogic-unit-test-modules/src/main/ml-modules/root/test/test-controller.xqy
> +			if ($xsl-match)
Keep the "then" on the same line to minimize line changes.

2023-08-09 16:25 UTC, rjrudin commented on marklogic-unit-test-modules/src/main/ml-modules/root/test/test-controller.xqy
> +				for $result at $idx in $test/test:result[@type = "fail"]
Is this a bug fix here? The code was previously only looking at the first test result, which may not have failed, but the second or later result may have failed?

2023-08-09 16:26 UTC, rjrudin commented on marklogic-unit-test-modules/src/main/ml-modules/root/test/test-controller.xqy
> +				for $result at $idx in $test/test:result[@type = "fail"]
Also, I'm not sure if this is valid JUnit legacy XML. Doing some googling to see if multiple `failure` elements are allowed within a `testcase` element.

2023-08-09 16:35 UTC, rjrudin commented on marklogic-unit-test-client/src/test/java/com/marklogic/test/unit/SampleParameterizedTest.java
> +    TestSuiteResult result = testManager.run(testModule);
Also missing a brace in this class - I had to add one, wasn't compiling otherwise.

2023-08-10 06:49 UTC, closed without merging

2023-08-10 06:49 UTC, peetkes commented
Does not make sense